@url=http://localhost:5050/admin
@json=Content-Type: application/json
@token=Authorization: Bearea eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGMzNjllYzI5OTc2MWIxN2FmYzdmY2EiLCJpYXQiOjE2MjM5MDE1MDIsImV4cCI6MTYyMzkwMTUzMn0.lz1WIs__xH1atKTMvmg2HcLMNV1_X97zFWwBSz0btrA

###
get {{url}} HTTP/1.1

###
POST {{url}}/users HTTP/1.1
{{json}}

{
  "username":"qazqsx753",
  "phone":"222",
  "password":"123"
}

###
POST {{url}}/login HTTP/1.1
{{json}}

{
  "username":"qazqsx753",
  "password":"123"
}

###
get {{url}}/users HTTP/1.1
{{json}}
{{token}}